application: 'bill-lab'
runtime: java7
version: 'web-1375817297'
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: '1.0'
handlers:
- url: (/cron/.*\.nocache\..*\.cache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 0s
- url: (/cron/.*\.cache\..*\.nocache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 0s
- url: (/.*\.nocache\..*\.cache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: required
  secure: optional
  expiration: 0s
- url: (/cron/.*\.cache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 365d
- url: (/cron/.*\.nocache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 0s
- url: (/cron)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
- url: (/.*\.cache\..*\.nocache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: required
  secure: optional
  expiration: 0s
- url: (/.*\.cache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: required
  secure: optional
  expiration: 365d
- url: (/.*\.nocache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: required
  secure: optional
  expiration: 0s
- url: (/cron/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: required
  secure: optional
- url: /cron/
  script: unused
  login: admin
  secure: optional
- url: /edit
  script: unused
  login: required
  secure: optional
- url: /cron/.*/
  script: unused
  login: admin
  secure: optional
- url: /download
  script: unused
  login: required
  secure: optional
- url: /_ah/.*
  script: unused
  login: required
  secure: optional
- url: /.*/
  script: unused
  login: required
  secure: optional
- url: /post
  script: unused
  login: required
  secure: optional
- url: /upload
  script: unused
  login: required
  secure: optional
- url: /cron/.*\.jsp
  script: unused
  login: admin
  secure: optional
- url: /
  script: unused
  login: required
  secure: optional
- url: /cron/clean
  script: unused
  login: admin
  secure: optional
- url: /.*\.jsp
  script: unused
  login: required
  secure: optional
- url: .*\.jsp
  script: unused
  login: optional
  secure: optional
- url: /_ah/spi/.*
  script: unused
  login: optional
  secure: optional
